//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace Microsoft.Office.WopiValidator.Core
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ct_wopi-discovery")]
	[System.Xml.Serialization.XmlRootAttribute("wopi-discovery", Namespace = "", IsNullable = false)]
	public partial class ct_wopidiscovery
	{

		private ct_netzone[] netzoneField;

		private ct_proofkey proofkeyField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("net-zone")]
		public ct_netzone[] netzone
		{
			get
			{
				return this.netzoneField;
			}
			set
			{
				this.netzoneField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("proof-key")]
		public ct_proofkey proofkey
		{
			get
			{
				return this.proofkeyField;
			}
			set
			{
				this.proofkeyField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ct_net-zone")]
	public partial class ct_netzone
	{

		private ct_appname[] appField;

		private st_wopizone nameField;

		private bool nameFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("app")]
		public ct_appname[] app
		{
			get
			{
				return this.appField;
			}
			set
			{
				this.appField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public st_wopizone name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool nameSpecified
		{
			get
			{
				return this.nameFieldSpecified;
			}
			set
			{
				this.nameFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ct_app-name")]
	public partial class ct_appname
	{

		private ct_wopiaction[] actionField;

		private string nameField;

		private string favIconUrlField;

		private bool checkLicenseField;

		public ct_appname()
		{
			this.checkLicenseField = false;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("action")]
		public ct_wopiaction[] action
		{
			get
			{
				return this.actionField;
			}
			set
			{
				this.actionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string favIconUrl
		{
			get
			{
				return this.favIconUrlField;
			}
			set
			{
				this.favIconUrlField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool checkLicense
		{
			get
			{
				return this.checkLicenseField;
			}
			set
			{
				this.checkLicenseField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ct_wopi-action")]
	public partial class ct_wopiaction
	{

		private st_wopiactionvalues nameField;

		private bool defaultField;

		private string requiresField;

		private string urlsrcField;

		private string extField;

		private string progidField;

		private string newprogidField;

		private string newextField;

		private bool useParentField;

		private string targetextField;

		public ct_wopiaction()
		{
			this.defaultField = false;
			this.useParentField = false;
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public st_wopiactionvalues name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool @default
		{
			get
			{
				return this.defaultField;
			}
			set
			{
				this.defaultField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string requires
		{
			get
			{
				return this.requiresField;
			}
			set
			{
				this.requiresField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string urlsrc
		{
			get
			{
				return this.urlsrcField;
			}
			set
			{
				this.urlsrcField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ext
		{
			get
			{
				return this.extField;
			}
			set
			{
				this.extField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string progid
		{
			get
			{
				return this.progidField;
			}
			set
			{
				this.progidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string newprogid
		{
			get
			{
				return this.newprogidField;
			}
			set
			{
				this.newprogidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string newext
		{
			get
			{
				return this.newextField;
			}
			set
			{
				this.newextField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(false)]
		public bool useParent
		{
			get
			{
				return this.useParentField;
			}
			set
			{
				this.useParentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string targetext
		{
			get
			{
				return this.targetextField;
			}
			set
			{
				this.targetextField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "st_wopi-action-values")]
	public enum st_wopiactionvalues
	{

		/// <remarks/>
		view,

		/// <remarks/>
		edit,

		/// <remarks/>
		mobileView,

		/// <remarks/>
		embedview,

		/// <remarks/>
		embededit,

		/// <remarks/>
		mobileclient,

		/// <remarks/>
		present,

		/// <remarks/>
		presentservice,

		/// <remarks/>
		attend,

		/// <remarks/>
		attendservice,

		/// <remarks/>
		editnew,

		/// <remarks/>
		imagepreview,

		/// <remarks/>
		interactivepreview,

		/// <remarks/>
		formsubmit,

		/// <remarks/>
		formedit,

		/// <remarks/>
		rest,

		/// <remarks/>
		preloadview,

		/// <remarks/>
		preloadedit,

		/// <remarks/>
		rtc,

		/// <remarks/>
		getinfo,

		/// <remarks/>
		convert,

		/// <remarks/>
		syndicate,

		/// <remarks/>
		legacywebservice,

		/// <remarks/>
		collab,

		/// <remarks/>
		formpreview,

		/// <remarks/>
		documentchat,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ct_proof-key")]
	public partial class ct_proofkey
	{

		private string exponentField;

		private string modulusField;

		private string oldexponentField;

		private string oldmodulusField;

		private string oldvalueField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string exponent
		{
			get
			{
				return this.exponentField;
			}
			set
			{
				this.exponentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string modulus
		{
			get
			{
				return this.modulusField;
			}
			set
			{
				this.modulusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string oldexponent
		{
			get
			{
				return this.oldexponentField;
			}
			set
			{
				this.oldexponentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string oldmodulus
		{
			get
			{
				return this.oldmodulusField;
			}
			set
			{
				this.oldmodulusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string oldvalue
		{
			get
			{
				return this.oldvalueField;
			}
			set
			{
				this.oldvalueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "st_wopi-zone")]
	public enum st_wopizone
	{

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("internal-http")]
		internalhttp,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("internal-https")]
		internalhttps,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("external-http")]
		externalhttp,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("external-https")]
		externalhttps,
	}
}
